# Generated by Django 5.1.2 on 2024-10-29 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
